/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/neoT5RbXQY7
 */
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export function Login() {
  return (
    <>
      <div className='flex items-center justify-center py-12'>
        <div className='mx-auto grid w-[350px] gap-6 z-30'>
          <div className='grid gap-2 text-center'>
            <h1 className='text-3xl font-bold text-primary'>Login</h1>
            <p className='text-balance text-gray-500 dark:text-gray-400'>
              Enter your email below to login to your account
            </p>
          </div>
          <div className='grid gap-4'>
            <div className='grid gap-2'>
              <Label htmlFor='email'>Email</Label>
              <Input
                id='email'
                placeholder='m@example.com'
                required
                type='email'
              />
            </div>
            <div className='grid gap-2'>
              <div className='flex items-center'>
                <Label htmlFor='password'>Password</Label>
              </div>
              <Input id='password' required type='password' />
              <Link
                className='underline underline-offset-2 ml-2 text-gray-900 text-sm dark:text-gray-50'
                href='#'
              >
                Forgot your password?
              </Link>
            </div>
            <Button className='w-full bg-primary' type='submit'>
              Login
            </Button>
            <Button className='w-full' variant='outline'>
              Login with Google
            </Button>
          </div>
          <div className='mt-4 text-center text-sm'>
            Don't have an account?{' '}
            <Link className='underline' href='/signup'>
              Sign up
            </Link>
          </div>
        </div>
      </div>
      <div className='hidden bg-repeat lg:flex items-center justify-center relative dark:bg-gray-800 font-semibold text-7xl text-primary select-none'>
        <p className='outline-4 outline p-4 z-10'>YoloHome</p>
      </div>
    </>
  )
}
